/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  games: [
    {
      type: 'category',
      label: 'Gamer Resources',
      link: {type: 'doc', id: 'intro'},
      items: [
        'photoshop/fonts-brushes',
        'photoshop/coins',
        'photoshop/wax-seals',
        'photoshop/crest',
        'photoshop/wow-logo',
        'photoshop/event-maps',
      ]
    },
    {
          type: 'category',
          label: 'Event Guides',
          link: {type: 'doc', id: 'events-campaigns'},
          items: [
            'investigations',
            'stealth',
            'horror',
            'onepage'
          ]
    },
    {
      type: 'category',
      label: 'Journals and Scrolls',
      link: {
        type: 'doc',
        id: 'photoshop/journals',
      },
      items: [
        'photoshop/adventure-journal',
        'photoshop/tech-journals',
        'photoshop/final-journal',
        'photoshop/elven-journal',
        'photoshop/dwarf-journal',
        'photoshop/arden-journal',
        'photoshop/vampire-journal',
        'photoshop/jungle-journal',
        'photoshop/alterac-journal',
        'photoshop/scrollcase',
        'photoshop/posters',
      ]
    },
    {
      type: 'category',
      label: 'Warcraft Resources',
      link: {type: 'doc', id: 'wow-conquest/intro'},
      items: [
        'photoshop/wow-emoji',
        'wow-conquest/token',
        'wow-conquest/capture-assets',
        'wow-conquest/simple-token',
        'wow-conquest/create-ship',
        'wow-conquest/squad-token',
        'wow-conquest/event-cards',
        'wow-conquest/boss-item-cards'
      ],
    },
    {
      type: 'category',
      label: 'Exalted',
      link: {type: 'doc', id: 'exalted/resources'},
      items: [
        {
          type: 'category',
          label: 'Campaigns',
          items: [
            'exalted/ghosts-south',
            'exalted/ascending-souls',
          ]
        },
        {
          type: 'category',
          label: 'South',
          items: [
            'exalted/chiaroscuro',
            'exalted/trade-routes',
            'exalted/society',
            'exalted/markets',
            'exalted/groups',
            'exalted/delzahn',
          ]
        },
        'exalted/timelines'
      ],
    },
    {
      type: 'category',
      label: 'World of Darkness',
      link: {type: 'doc', id: 'w-o-d/intro'},
      items: [
      'w-o-d/suicide-kings',
      {
        type: 'category',
        label: 'Vampire Domains',
        items: ['w-o-d/domains', 'w-o-d/create-domain', 'w-o-d/merits-flaws', 'w-o-d/domain-rules', 'w-o-d/example-domain'],
      }
    ]
    },
  ],
};
