/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  games: [
    'intro',
    {
      type: 'category',
      label: 'Dungeons and Dragons',
      items: ['d-n-d/intro'],
    },
    {
      type: 'category',
      label: 'Warcraft',
      items: [
        'wow-conquest/intro',
        {
          type: 'category',
          label: 'Vehicle Tokens',
          items: ['wow-conquest/token', 'wow-conquest/create-ship'],
        },
      ],
    },
    {
      type: 'category',
      label: 'World of Darkness',
      items: ['w-o-d/intro'],
    },
    {
      type: 'category',
      label: 'Shadowrun',
      items: ['shadowrun/intro'],
    },
  ],
  tutorials: [
    'tutorials/intro'
  ]
};
